(function(){function e(a){try{var a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),b=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.href);return b==null?"":b[1]}catch(c){f.track(h+"getQuerystring",{stack:c.stack,msg:c.message})}}function v(a,b,c){try{var d=document.createElement("script");d.type="text/javascript";d.src=a;if(c)d.async=!0;d.readyState?d.onreadystatechange=function(){if(d.readyState=="loaded"||d.readyState=="complete")d.onreadystatechange=null,b()}:d.onload=function(){b()};document.getElementsByTagName("head")[0].appendChild(d)}catch(i){f.track(h+
"attachScript",{stack:i.stack,msg:i.message})}}function w(a){try{switch(a.creativeTypeId){case 1:if(a.imageUrl&&a.imageUrl.indexOf(".swf",a.imageUrl.length-4)!==-1){var b="swfContent"+Math.floor(Math.random()*1E6);document.write("<div id='"+b+"'></div>");v("//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js",function(){try{if(typeof alreadyEmbeded=="undefined"){alreadyEmbeded=!0;var d={clickTag:encodeURIComponent(a.clickUrl)};swfobject.embedSWF(a.imageUrl+"?clickTag="+encodeURIComponent(a.clickUrl),
b,admatter_width,admatter_height,"10.0.0","expressInstall.swf",d,{menu:"false",allowScriptAccess:"always",wmode:"opaque"},{style:"outline:none;background-color:#FFFFFF"})}}catch(i){f.track(h+"processResponse.swf",{stack:i.stack,msg:i.message})}})}else document.write("<a href='"+a.clickUrl+"' target='_blank' rel='nofollow'><img src='"+a.imageUrl+"' border='0' /></a>");document.write("<script type='text/javascript' src='"+a.impressionUrl+"'><\/script>");break;case 6:if(a.campaignId)j=a.campaignId,k=
a.adId;if(a.rootToken)l=a.rootToken;document.write(a.impressionUrl);break;default:case 3:if(a.campaignId)j=a.campaignId,k=a.adId;if(a.rootToken)l=a.rootToken;document.write(a.html);document.write("<script type='text/javascript' src='"+a.impressionUrl+"'><\/script>")}typeof sendMsg=="function"&&sendMsg(a.campaignId);a.sv&&typeof checkKLVersion=="function"&&checkKLVersion(a.sv)}catch(c){console&&console.debug&&console.debug(c.message),f.track(h+"processResponse",{stack:c.stack,msg:c.message})}}function q(){try{renderCreative=
w;r=typeof YontooClient!="undefined"&&typeof YontooClient.getInstallId!="undefined"?YontooClient.getInstallId():e("clientId");typeof admatter_uid=="undefined"||admatter_uid===""?admatter_uid=m=e("uid"):m=admatter_uid;g=e("r");s=e("l");t=e("st");n=e("kw");u=e("itc");o=e("cat");admatter_adid=k;admatter_campaignid=j;admatter_retryCounter=p;admatter_rootToken=l;admatter_searchTerm=decodeURIComponent(t);admatter_referrer=decodeURIComponent(g);admatter_pageUrl=decodeURIComponent(s);admatter_keyword=decodeURIComponent(n);
admatter_category=decodeURIComponent(o);var a="uid="+m+"&amp;p="+admatter_account+"&amp;slot="+admatter_slot+"&amp;cid="+r+"&amp;adtype="+admatter_adtype+"&amp;width="+admatter_width+"&amp;height="+admatter_height+"&amp;kw="+n+"&amp;cat="+o+"&amp;ua="+encodeURIComponent(navigator.userAgent.length>1024?navigator.userAgent.substring(0,1024):navigator.userAgent)+"&amp;rfr="+encodeURIComponent(g.length>1024?g.substring(0,1024):g)+"&amp;ry="+p+"&amp;cit="+j+"&amp;ait="+k+"&amp;itc="+u+"&amp;rt="+l+"&amp;bust="+
Math.floor(Math.random()*1E4);document.write("<script type='text/javascript' src='//service.amasvc.com/creative.jsonp?"+a.replace(/'/g,"%27")+"'><\/script>")}catch(b){f.track(h+"init",{stack:b.stack,msg:b.message})}}var k=0,j=0,p=0,l="",t="",g="",s="",n="",o="",h="showads-err",u=0,r="",m="";admatter_retryCounter=admatter_campaignid=admatter_adid=0;admatter_category=admatter_keyword=admatter_pageUrl=admatter_referrer=admatter_searchTerm=admatter_rootToken="";processPassback=function(){p++;q()};var f=
function(){return{track:function(a,b){try{typeof mixpanel=="undefined"&&function(a,b){window.mixpanel=b;var c,e,f;b._i=[];b.init=function(a,c,d){function h(a,b){var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(Array.prototype.slice.call(arguments,0)))}}var g=b;"undefined"!==typeof d?g=b[d]=[]:d="mixpanel";g.people=g.people||[];e="disable,track,track_pageview,track_links,track_forms,register,register_once,unregister,identify,alias,name_tag,set_config,people.set,people.set_once,people.increment,people.track_charge,people.append".split(",");
for(f=0;f<e.length;f++)h(g,e[f]);b._i.push([a,c,d])};b.__SV=1.2;c=a.createElement("script");c.type="text/javascript";c.async=!0;c.src=("https:"===a.location.protocol?"https:":"http:")+"//cdn.mxpnl.com/libs/mixpanel-2.2.min.js";a.getElementsByTagName("head")[0].appendChild(c)}(document,window.mixpanel||[]),Math.random()<0.01&&(mixpanel["adm-showads"]||mixpanel.init("39d9bda2d6f973544f9e7aed327ef670",{},"adm-showads"),mixpanel["adm-showads"].track(a,b))}catch(c){}}}}();q()})();
